"on":
  - push
  - pull_request
name: Test
jobs:
  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - uses: microsoft/playwright-github-action@v1
      - run: npm ci
      - run: npm test
